### ISSUE TITLE
Preview doesn't show anything

### ISSUE THREAD

**Issue by MrRaveYard** [disasteroftheuniverse/zdoom-navmesh-generator#1] opened 2022-11-05 15:45 UTC
I can't see anything like a level preview in the browser. Tried both Opera and Chrome, nothing.
But it does produce some kind of JSON file in the mesh directory if I click "Build navigation mesh"

![image](https://user-images.githubusercontent.com/29225776/200128046-21aca993-7999-4e68-b027-0b69a0e8be30.png)

Here's the server response I get when clicking "Load Level"
```
{"scene":{"metadata":{"version":4.5,"type":"Object","generator":"Object3D.toJSON"},"geometries":[{"uuid":"2fdf332c-2195-45ad-8ec6-4ea670c0c233","type":"BufferGeometry","userData":{"mergedUserData":[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}]},"data":{"attributes":{"position":{"itemSize":3,"type":"Float32Array","array":[-448,0,-64,-448,128,-64,-448,0,192,-448,128,192,-32,0,-448,-32,128,-448,-192,0,-448,-192,128,-448,224,0,112,224,128,112,224,0,32,224,128,32,128,0,112,128,128,112,-32,0,96,-32,128,96,-32,0,192,-32,128,192,0,0,32,0,128,32,0,0,96,0,128,96,-32,0,128,-32,128,128,0,0,128,0,128,128,0,0,192,0,128,192,128,0,192,128,128,192,-192,0,-64,-192,128,-64],"normalized":false}},"index":{"type":"Uint16Array","array":[0,1,2,2,1,3,4,5,6,6,5,7,8,9,10,10,9,11,12,13,8,8,13,9,14,15,4,4,15,5,2,3,16,16,3,17,18,19,20,20,19,21,22,23,24,24,23,25,10,11,18,18,11,19,16,17,22,22,17,23,24,25,26,26,25,27,26,27,28,28,27,29,28,29,12,12,29,13,30,31,0,0,31,1,6,7,30,30,7,31,20,21,14,14,21,15]}}},{"uuid":"43046b48-a0b9-495d-94ce-a25f9f3eff52","type":"BufferGeometry","userData":{"mergedUserData":[{},{},{}]},"data":{"attributes":{"position":{"itemSize":3,"type":"Float32Array","array":[-192,0,-64,-448,0,-64,-448,0,192,-32,0,192,-32,0,128,-32,0,96,-32,0,-448,-192,0,-448,0,0,128,0,0,96,0,0,192,128,0,192,128,0,112,224,0,112,224,0,32,0,0,32],"normalized":false}},"index":{"type":"Uint16Array","array":[0,1,2,2,3,4,5,6,7,0,2,4,4,5,7,7,0,4,5,4,8,8,9,5,8,10,11,12,13,14,14,15,9,9,8,11,12,14,9,9,11,12]}}}],"materials":[{"uuid":"bcdb9497-dbc8-4902-951a-e9fea4c8b5ae","type":"MeshBasicMaterial","color":1114146,"reflectivity":1,"refractionRatio":0.98,"depthFunc":3,"depthTest":true,"depthWrite":true,"colorWrite":true,"stencilWrite":false,"stencilWriteMask":255,"stencilFunc":519,"stencilRef":0,"stencilFuncMask":255,"stencilFail":7680,"stencilZFail":7680,"stencilZPass":7680},{"uuid":"e730b06b-ed55-4d2b-a30f-a7b1c3b44af8","type":"MeshBasicMaterial","color":1114146,"reflectivity":1,"refractionRatio":0.98,"side":2,"depthFunc":3,"depthTest":true,"depthWrite":true,"colorWrite":true,"stencilWrite":false,"stencilWriteMask":255,"stencilFunc":519,"stencilRef":0,"stencilFuncMask":255,"stencilFail":7680,"stencilZFail":7680,"stencilZPass":7680}],"object":{"uuid":"06b63b17-9fb3-45d8-a32b-971ef067d43e","type":"Scene","layers":1,"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"children":[{"uuid":"e35aed51-2e1d-42f8-abdc-3affb355b6dd","type":"Object3D","layers":1,"matrix":[0.015625,0,0,0,0,0.015625,0,0,0,0,0.015625,0,0,0,0,1],"children":[{"uuid":"44d9bb3d-4be9-4132-b5ab-f2d4d80a608a","type":"Object3D","name":"walls.preview","layers":1,"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"children":[{"uuid":"d5b35c7f-2cd7-48da-b9c2-da99c6769820","type":"Mesh","name":"walls.preview","layers":1,"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"geometry":"2fdf332c-2195-45ad-8ec6-4ea670c0c233","material":"bcdb9497-dbc8-4902-951a-e9fea4c8b5ae"}]},{"uuid":"8783a2ce-1490-4796-9878-4534a590abf1","type":"Mesh","name":"floors","layers":1,"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],"geometry":"43046b48-a0b9-495d-94ce-a25f9f3eff52","material":"e730b06b-ed55-4d2b-a30f-a7b1c3b44af8"},{"uuid":"94fbce0f-ad53-4e28-936d-6ced157287ce","type":"Object3D","name":"nav.nodes","layers":1,"matrix":[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}]}]}},"config":{"triangulation_algorithms":["libtess","earcut","delaunay","smallest"],"triangulation":"libtess","options":{"cellSize":0.25,"cellHeight":0.1,"agentHeight":1,"agentRadius":0.5,"agentMaxClimb":0.30000000000000004,"agentMaxSlope":40,"regionMinSize":12,"regionMergeSize":32,"edgeMaxLen":16,"edgeMaxError":2.5},"merge_distance":1,"solo":true}}
```
and the browser console shows:
![image](https://user-images.githubusercontent.com/29225776/200126864-ab3b1a25-74ad-42d4-a36b-18859ba79b14.png)

server messages when clicking load level:
![image](https://user-images.githubusercontent.com/29225776/200128002-db767ed1-0094-4759-a259-875678efef87.png)

and the map I tested it on:
[MAP01.zip](https://github.com/disasteroftheuniverse/zdoom-navmesh-generator/files/9944165/MAP01.zip)

**Comment by disasteroftheuniverse** [comment] 2022-11-06 01:14
hmm, the path names need to be full file paths, can you confirm that's the case?

**Comment by MrRaveYard** [comment] 2022-11-06 09:52
I configured full paths and restarted the server, behaves exactly as before. Is there any other kind of information you need or test I can try?

I also tried that on Firefox, Edge, Chrome, Opera... still nothing.

**Comment by disasteroftheuniverse** [comment] 2022-11-06 13:59
I'll dig into this more when I am at my computer.  I'll take a closer look at this later, the scene object that you posted, however, does not appear to contain any geometry data in it. This tells me that the problem is not in the browser, but that's something with the server or the parser is messing up.

**Comment by disasteroftheuniverse** [comment] 2022-11-06 21:26
![image](https://user-images.githubusercontent.com/13474848/200195974-c01883cf-9d37-4e0d-a8c0-b4f4144b018a.png)
@MrRaveYard I was not able to replicate the issue. it works just fine for me. Did you click the 'load level' button at the top? Also, you can use WASD controls to fly around. try looking around and flying around to see if your level is visible anywhere.

**Comment by disasteroftheuniverse** [comment] 2022-11-07 12:35
closing this because I am unable to replicate the issue.

**Closed as completed by disasteroftheuniverse** 2022-11-07 12:35 UTC

**Comment by MrRaveYard** [comment] 2022-11-07 22:47
@disasteroftheuniverse  Ah, thanks. It was the WASD to move around... I feel to stupid.

**Comment by disasteroftheuniverse** [comment] 2022-11-08 00:30
Happens to the best of us. Just glad there wasn't some weird issue I had to chase down.
